name: CICD
on:
  push:
    branches: [ "lab04" ]
  pull_request:
    branches: [ "lab04" ]
  workflow_dispatch:
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run Tests
        run: python -m unittest tests/unit_tests.py
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run Tests
        run: python -m unittest tests/unit_tests.py
